version: '3'
services:
    backend:
        build: ./
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./src:/src
    database:
        image: postgres
        environment:
            POSTGRES_USER: todo
            POSTGRES_PASSWORD: todo
