version: '3'
services:
    service:
        build: ./service
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - ./service:/src
    database:
        image: postgres
        environment:
            POSTGRES_USER: todo
            POSTGRES_PASSWORD: todo
